name: build

on: workflow_dispatch

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Get playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(cat node_modules/playwright/package.json | jq -r '.version')
          echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

      - name: Cache playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install --with-deps

      - name: Generate features
        run: bun run build:features

      - name: Generate homepage
        run: bun run build:homepage

      - name: Prepare dist
        run: |
          mkdir -p ./dist
          mv ./homepage/* ./dist/
          mv ./features/ ./dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: pages
          token: ${{ secrets.GITHUB_TOKEN }}
